/// {@template storage}
/// This folder contains the storage related code.
///
/// The main implementation uses Firebase Storage and Firebase Auth
/// with custom tokens generated by the GraphQL API.
///
/// Process to get the resource:
/// 1. Get the token with the [IStorageAuthRepository]
/// 2. Add the token to repository with the [IStorageRepository.setToken]
/// 3. Get the resource from the repository.
/// {@endtemplate}
library;

import 'package:spk_app_frontend/common/storage/repositories/interfaces.dart';

export './errors/errors.dart';
export './repositories/interfaces.dart';
export './repositories/repositories.dart';
